spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_tracker
spring.datasource.password=Postgre@4722
spring.datasource.username=postgres

server.port=4722

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
